[package]
name = "rust_src"
version = "0.1.0"
authors = ["Alexander Maloney <maloney.a12@gmail.com>"]

[dependencies]
lib_composite = {path = "/home/vagrant/lib_composite"}
lazy_static = "1.0.0"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
