[system]
description = "Synchronous IPC between threads test."

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "syncipc"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "client"
img  = "tests.bench_syncipc_cli"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "sched", interface = "syncipc"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "pong", interface = "pong"}]
constructor = "booter"

[[components]]
name = "server"
img  = "tests.bench_syncipc_srv"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "sched", interface = "syncipc"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "pong", interface = "pong"}]
constructor = "booter"

[[components]]
name = "pong"
img  = "pong.pingpong"
deps = [{srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
implements = [{interface = "pong"}]
constructor = "booter"

[[address_spaces]]
name = "system"
components = ["capmgr", "sched"]
 
[[address_spaces]]
name = "bench"
components = ["client", "server"]
parent = "system"

[[address_spaces]]
name = "pong"
components = ["pong"]
parent = "system"
