[system]
description = "Simple UDP memcached server"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}, {interface = "contigmem"}]
constructor = "booter"
baseaddr = "0x1400000"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "syncipc"}, {interface = "init"}]
constructor = "booter"
baseaddr = "0x1600000"

[[components]]
name = "nicmgr"
img  = "nicmgr.dpdk"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}]
implements = [{interface = "nic"}]
constructor = "booter"
baseaddr = "0x6000000"

[[components]]
name = "memcached"
img  = "memcached.memcached"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}]
implements = [{interface = "mc"}]
constructor = "booter"
baseaddr = "0x2600000"

[[components]]
name = "simple_mc_udp_server1"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x6000000"

[[components]]
name = "simple_mc_udp_server2"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x7000000"

[[components]]
name = "simple_mc_udp_server3"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x8000000"

[[components]]
name = "simple_mc_udp_server4"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x9000000"

[[components]]
name = "simple_mc_udp_server5"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0xA000000"

[[components]]
name = "simple_mc_udp_server6"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0xB000000"

[[components]]
name = "simple_mc_udp_server7"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0xC000000"

[[components]]
name = "simple_mc_udp_server8"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0xD000000"

[[components]]
name = "simple_mc_udp_server9"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0xE000000"

[[components]]
name = "simple_mc_udp_server10"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0xF000000"

[[components]]
name = "simple_mc_udp_server11"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x10000000"

[[components]]
name = "simple_mc_udp_server12"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x11000000"

[[components]]
name = "simple_mc_udp_server13"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x12000000"

[[components]]
name = "simple_mc_udp_server14"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x13000000"

[[components]]
name = "simple_mc_udp_server15"
img  = "simple_mc_udp_server.simple_mc_udp_server_no_lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"},{srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}, {srv = "memcached", interface = "mc"}]
constructor = "booter"
baseaddr = "0x14000000"
