[system]
description = "Simple UDP memcached server"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
baseaddr = "0x1600000"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
baseaddr = "0x1800000"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}, {interface = "contigmem"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
baseaddr = "0x2000000"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "syncipc"}, {interface = "init"}]
constructor = "booter"
baseaddr = "0x1600000"

[[components]]
name = "xcpu_sem"
img  = "tests.unit_xcpu_sem"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}]
constructor = "booter"
baseaddr = "0x6000000"
