[system]
description = "Simple ipi test with one thread trying to wakeup another thread running on another core."

[[components]]
name = "booter"
img  = "no_interface.llbooter"
baseaddr = "0x1600000"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
baseaddr = "0x1800000"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
baseaddr = "0x2000000"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "schedtest"
img  = "tests.unit_slitetest"
baseaddr = "0x2200000"
deps = [{srv = "sched", interface = "init"}, {srv = "sched", interface = "sched"}, {srv = "capmgr", interface = "capmgr_create"}]
constructor = "booter"

[[address_spaces]]
name = "system"
components = ["capmgr", "sched"]

[[address_spaces]]
name = "test"
components = ["schedtest"]
parent = "system"
