[package]
name = "rust_src"
version = "0.1.0"
authors = ["Alexander Maloney <maloney.a12@gmail.com>"]

[dependencies]
lib_composite = {path = "/home/maloneya/SD/lib_composite"}

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
